### PR TITLE
Update mcr.cpp

### PR DESCRIPTION
**Pull request by xunchelai**
1.The game board is initialized properly to ensure all cells are empty. 2.Added checks to ensure that players cannot 
3.Winning Condition Check

### CODE REVIEW

**Review by npusamuelsun — COMMENTED** [review]
Good, pass

**Review by MuBai-Argo — COMMENTED** [review]
pass

**Review by junyishen3 — COMMENTED** [review]
pass

**Review by GN-H — COMMENTED** [review]
ok

**Review by whetheryoulikeornot — COMMENTED** [review]
pass

**Pull request merged**
